services:
    marttiphpbb.scssdev.listener:
        class: marttiphpbb\scssdev\event\listener
        arguments:
            - '@language'
            - '@user'
            - '@config'
            - '@auth'
            - '@request'
            - '@ext.manager'
            - '@service_container'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
