services:
    marttiphpbb.themecolordev.listener:
        class: marttiphpbb\themecolordev\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@template.twig.loader'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

