services:
    marttiphpbb.scssthemedev.listener:
        class: marttiphpbb\scssthemedev\event\listener
        arguments:
            - '@language'
            - '@user'
            - '@config'
            - '@auth'
            - '@request'
            - '@template.twig.loader'
            - '@ext.manager'
            - '@service_container'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
